import Footer from "../components/Footer"
import Header from "../components/Header"
import Sidebar from "../components/Sidebar"

export const metadata = {
    title: 'Dashboard',
    description: 'Generated by create next app',
}

export default function DashboardLayout({ children }) {
    return (
        <div id="main-wrapper" className="dashboard_admin show">
            <Header />
            <Sidebar />

            <div className="content-body">
                <div className="main-content">
                    {children}
                </div>
            </div>

            <Footer />
        </div>
    )
}